### ISSUE TITLE
Camera HDR support

### ISSUE THREAD

**Issue by A-Shahbazi** [CyanogenMod/android_device_huawei_kiwi#4]
Can't we use [kipper](http://wiki.cyanogenmod.org/w/Kipper_Info) camera HAL to fix the issue?
The camera HAL of the device the code was forked from first([tomato-YU Yureka](http://wiki.cyanogenmod.org/w/Tomato_Info)) seems to be switched to kipper([see here](https://github.com/CyanogenMod/android_device_yu_tomato/commits/cm-13.0/camera)).

**Comment by A-Shahbazi** [comment]
@crpalmer @BadDaemon

**Comment by BadDaemon** [comment]
How about doing the work yourself instead of tagging ppl to do the work for you?

**Comment by A-Shahbazi** [comment]
People!?
You mean recent contributors to the project!?
BTW, I don't have the phone yet!

Anyway, how about shutting your mouth if you're not going to do anything about it!?
