### ISSUE TITLE
Can you bring up Cm-14.0 on device ?

### ISSUE THREAD

**Issue by kaanyigitkulahli** [CyanogenMod/android_device_huawei_kiwi#5]
Hello, I seen cm-14.0 branch. But I don't see now?. Can you get cm 14 on device ?.

@crpalmer  @razorloves @BadDaemon

**Comment by kaanyigitkulahli** [comment]
? Can you help please ?

**Comment by kaanyigitkulahli** [comment]
@BadDaemon  you answerd other question. You see my issue please .

**Comment by Anik1199** [comment]
Hey! Developers does this job on his free time. They just can't answer when and you should get it. They aren't paid for doing this job. So when they feel free to do they will do it.

**Comment by kaanyigitkulahli** [comment]
yes I know but I have passed 28 days ago. Did you ever think you have no leisure time?
